[package]
name = "weatherlink-data-logger"
version = "0.0.1"
authors = ["jason a. grafft <j@grafft.co>"]
edition = "2018"

[dependencies]
#diesel = { version = "*", features = ["postgres"] }
#dotenv = "*"
serde_json = "*"
