[package]
name = "weatherlink-data-logger"
version = "0.0.1"
authors = ["jason a. grafft <j@grafft.co>"]
edition = "2018"

[dependencies]
dotenv = "*"
#postgres = "*"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
serde_json = "*"
