[weatherlink]
keys_to_retain = [
  "bar_sea_level",
  "dew_point",
  "hum",
  "hum_in",
  # "solar_rad",
  "temp",
  "temp_in",
  "timestamp",
  # "uv_index",
  "wind_dir_last",
  "wind_speed_last",
]
request_interval = 9.5
request_timeout = 5 # seconds
# url = "http://hoveringsquidworld69az.ydns.eu:19273/v1/current_conditions"
url = "http://httpbin.org/delay"

# [redis]
# database = 7
# host = "127.0.0.1"
# port = 6379
# stream_prefix = "weatherlink"
