[dbs]
[dbs.redis]
database=0
host="localhost"
port=6379
stream_name="wlink"

[weatherlink]
interval = 8.5
keys_to_retain = [ "bar_sea_level", "dew_point", "hum", "hum_in", "solar_rad", "temp", "temp_in", "timestamp", "uv_index", "wind_dir_last", "wind_speed_last" ]
path = "/v1/current_conditions"
url = "<URL>"